# Numpy Basic Operations

In [11]:
import numpy as np

1. Create a 1D NumPy array containing the integers from 0 to 9.

In [1]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 2D NumPy array (3x3) containing random integers between 1 and 20.

In [40]:
randomNumbers = np.random.randint(1, 21, size=9)
array2D=randomNumbers.reshape(3,3)
print(array2D)
#second Method
array2=np.random.randint(1,21,(3,3))
print(array2)

[[11  7  3]
 [ 1  9 13]
 [ 7 17 15]]
[[ 6 18 12]
 [18  8 13]
 [ 6  3  5]]


3. Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.


In [4]:
array3D=np.ones((2,3,4),dtype='int')
print(array3D)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

4. Add two 1D arrays element-wise.


In [6]:
array1=np.array([1,2,3,4,5])
array2=np.array([1,2,3,4,5])
print(array1+array2)

array([ 2,  4,  6,  8, 10])

5. Multiply two 2D arrays element-wise.


In [14]:
array1=np.arange(1,10).reshape(3,3)
array2=np.arange(21,30).reshape(3,3)
array1*array2

array([[ 21,  44,  69],
       [ 96, 125, 156],
       [189, 224, 261]])

6. Calculate the dot product of two matrices.

In [2]:
array1=np.arange(1,10).reshape(3,3)
array2=np.arange(21,30).reshape(3,3)
np.dot(array1,array2)

array([[150, 156, 162],
       [366, 381, 396],
       [582, 606, 630]])

7. Calculate the mean, median, and standard deviation of a 1D array.


In [3]:
array=np.arange(1,21)
print(np.mean(array))
print(np.median(array))
print(np.std(array))

10.5
10.5
5.766281297335398


8. Find the maximum and minimum values in a 2D array.


In [35]:
array=np.arange(1,10).reshape(3,3)

print(np.max(array))
print(np.min(array))

9
1


9. Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.


In [7]:
mean = 0
standardDeviation = 1
array=np.random.normal(mean,standardDeviation,1000)
print(array)

[ 9.47893989e-01  6.64161513e-01  1.84651107e-01  1.04977912e+00
  1.96962293e-01 -2.64259937e-01 -1.03750989e+00  8.25230807e-01
 -4.58731255e-03 -6.51414790e-01 -4.47193342e-01  3.68984480e-01
  1.01311337e+00  5.91028573e-01  2.90058948e-01  9.92770621e-01
 -1.44637540e-01  9.11453511e-02  2.71435477e-01  1.02312060e+00
 -5.44893155e-01 -6.74795409e-01 -1.60761794e+00 -8.13445054e-02
  5.12015392e-01 -2.14181045e+00 -2.47830203e-01  1.28880820e-01
  2.00598939e+00  5.14658251e-01 -3.51214864e-01 -1.35362764e+00
  1.44709298e+00  8.35020712e-01  1.99019964e+00 -9.29084162e-01
 -2.12997320e-01  9.50954346e-02 -2.31810263e-01  9.57759201e-01
 -4.47914519e-02 -1.81238629e+00  2.92006777e-01 -4.48564852e-02
  1.30435151e+00  1.05603445e+00  1.15163366e+00 -2.02938037e+00
  1.17177779e+00  1.48532859e+00  1.98239509e-01 -3.11851632e-01
  9.42374996e-01  7.01581124e-01  4.10482077e-01  5.44122522e-01
  8.45650623e-01  1.36365121e+00 -1.43203750e+00 -6.95300796e-01
  7.77791013e-01 -6.10398

10. Create a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50.
 

In [8]:
low = 10
high = 50

array=np.random.uniform(low,high,size=(5,5))

print(array)

[[10.25314728 13.06736572 27.69546894 12.51309488 28.03982309]
 [28.2050847  30.23719676 33.58449362 28.33342929 24.98300357]
 [34.84727165 24.76853221 28.84367486 17.9129399  32.94728979]
 [36.22314289 31.03129141 45.33812913 31.53493538 44.76899942]
 [46.34828966 28.41425097 48.20366646 31.3926488  37.54587001]]


11. Calculate the cumulative sum of a 1D array.


In [39]:
Array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.cumsum(Array))

[ 0  1  3  6 10 15 21 28 36 45]


12. Compute the correlation coefficient matrix of a 2D array.

In [4]:

array=np.random.randint(10,50,(5,5))
np.corrcoef(array)

array([[ 1.        , -0.40342487,  0.56437476, -0.18335464, -0.84135907],
       [-0.40342487,  1.        , -0.75627226,  0.47221525, -0.10739064],
       [ 0.56437476, -0.75627226,  1.        , -0.79296613, -0.18109872],
       [-0.18335464,  0.47221525, -0.79296613,  1.        ,  0.03657867],
       [-0.84135907, -0.10739064, -0.18109872,  0.03657867,  1.        ]])

13. Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.

In [44]:
outcomes = np.random.randint(1, 7, size=1000)
frequency = {}
for num in outcomes:
    if num in frequency:
        frequency[num] += 1
    else:
        frequency[num] = 1
print(frequency)

{1: 179, 4: 155, 3: 177, 5: 165, 2: 166, 6: 158}


# Extras

1. Choosing Random number from the given array

In [7]:
array=np.array([3,4,6,99,55,33,22,34,55])
np.random.choice(array)

99

2. Flattening the multi dimensional array into a 1D array

In [18]:
#
array=np.array([[1,1,1,3,4,5],[2,2,3,4,5,4],[1,2,2,4,5,3]])
array2=np.array([[[1,1,1,3,3,5],
                  [1,2,2,4,5,3],
                  [2,2,4,3,5,5]],
                 
                  [[1,2,2,4,5,3],
                   [1,2,2,4,5,3],
                   [1,2,2,4,5,3]]])
print(array.flatten())
print(array2.flatten())

[1 1 1 3 4 5 2 2 3 4 5 4 1 2 2 4 5 3]
[1 1 1 3 3 5 1 2 2 4 5 3 2 2 4 3 5 5 1 2 2 4 5 3 1 2 2 4 5 3 1 2 2 4 5 3]


3. Transposing the array (Transpose is an operator that switches rows into columns and vice versa)

In [16]:
array2=np.array([[[1,1,1,3,3,5],[1,2,2,4,5,3],[2,2,4,3,5,5],[1,2,2,4,5,3],[1,2,2,4,5,3]]])
np.transpose(array2)

array([[[1],
        [1],
        [2],
        [1],
        [1]],

       [[1],
        [2],
        [2],
        [2],
        [2]],

       [[1],
        [2],
        [4],
        [2],
        [2]],

       [[3],
        [4],
        [3],
        [4],
        [4]],

       [[3],
        [5],
        [5],
        [5],
        [5]],

       [[5],
        [3],
        [5],
        [3],
        [3]]])

4. Swaping axis of an array

In [20]:

array2=np.array([[[1,1,1,3,3,5],
                  [1,2,2,4,5,3],
                  [2,2,4,3,5,5]],
                 
                  [[1,2,2,4,5,3],
                   [1,2,2,4,5,3],
                   [1,2,2,4,5,3]]])
swappedArray = np.swapaxes(array2, 0, 1)
print(swappedArray)

[[[1 1 1 3 3 5]
  [1 2 2 4 5 3]]

 [[1 2 2 4 5 3]
  [1 2 2 4 5 3]]

 [[2 2 4 3 5 5]
  [1 2 2 4 5 3]]]


5. Initializing an array filled with specific value

In [10]:

array = np.full((2, 3), False)
print(array)

[[False False False]
 [False False False]]
