---
<h1 align = 'center'><font color = "#967BB6">Linear algebra and calculus in NumPy</font></h1>  

---

---
<h1 align = center> Importing Necessary Libraries </h1>

---

In [1]:
import numpy as np


---
<h1 align = center><font color = #5865F2 >Linear Algebra Tasks</font></h1>

---


---
<h1 align = center><font color =#D462FF > 1. Matrix Creation and Manipulation</font></h1>

---


---
<h2 align = center><font color =#CC338B >Create various types of matrices (zero matrix, identity matrix, random matrix).</font></h2>

---

---
<h2 align = center><font color = '#F62217'> Zero Matrix</font></h2>

---

#### What is Zero Matrix

A zero matrix is a matrix in which all the elements are zero. It is a special case of a square matrix.

In [5]:
# making a zero matrix of size 3x3
zeroMatrix = np.zeros(shape=(3,3), dtype='int32')
zeroMatrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

---
<h2 align = center><font color = '#FF7900'> Identity Matrix</font></h2>

---

#### What is Identity Matrix ?

An identity matrix is a square matrix in which all the elements on the principal diagonal are ones (1s) and all other elements are zeros. It is also known as a unit matrix.

In [6]:
# making identity matrix of size 3x3

identityMatrix = np.eye(3, dtype='int32')
identityMatrix


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

---
<h2 align = center><font color = '#2672FF'> Random Matrix</font></h2>

---


#### What is Random Matrix ?

A random matrix is a matrix in which the elements are randomly generated numbers. It is often used in various applications, such as simulations, machine learning, and data analysis.

In [7]:
# making a random matrix of size 5x5

randomMatrix = np.random.randint(1, 25, size=(5,5), dtype='int32')
randomMatrix


array([[ 3, 14,  2, 12, 15],
       [21,  8, 24, 15,  5],
       [ 9,  3, 17, 11, 12],
       [21, 22, 12, 13, 15],
       [ 7, 18, 15, 19, 23]], dtype=int32)

---
<h2 align = center><font color =#CC338B >Perform basic matrix operations (addition, subtraction, multiplication).
</font></h2>

---


---
<h2 align = center><font color = '#6AFB92'>Addition</font></h2>

---

In [12]:
# Making 2 Random 5x5 Matrix

mat1 = np.random.randint(1,100 , size=(5,5),dtype='int16')
mat2 = np.random.randint(1,100 , size=(5,5),dtype='int16')

# Showing Mat1 and Mat2

print(f"\nMatrix 1\n")
print(mat1)

print(f"\nMatrix 2\n")
print(mat2)

# Adding the matrices

mat3 = mat1+mat2

print(f"\nResultant Matrix\n")
print(mat3)



Matrix 1

[[ 5 42 39 93 68]
 [96 48 45 24 83]
 [80 26 77 63 78]
 [76 74 19 11 60]
 [98 73 62 40 33]]

Matrix 2

[[30 56 66 26 65]
 [90 53 77 77 24]
 [35 24 41 80 57]
 [25 83 61 22 85]
 [95 84 14 15 12]]

Resultant Matrix

[[ 35  98 105 119 133]
 [186 101 122 101 107]
 [115  50 118 143 135]
 [101 157  80  33 145]
 [193 157  76  55  45]]


---
<h2 align = center><font color = '#FF7900'>Subtraction</font></h2>

---


In [13]:

# Making 2 Random 5x5 Matrix

mat1 = np.random.randint(1,100 , size=(5,5),dtype='int16')
mat2 = np.random.randint(1,100 , size=(5,5),dtype='int16')

# Showing Mat1 and Mat2

print(f"\nMatrix 1\n")
print(mat1)

print(f"\nMatrix 2\n")
print(mat2)

# Subtracting the matrices

mat3 = mat1-mat2

print(f"\nResultant Matrix\n")
print(mat3)



Matrix 1

[[82  8 59 38 22]
 [72 62 74 97  4]
 [83 40 59 87 59]
 [56 56 28 74 10]
 [71 32 36 56 22]]

Matrix 2

[[33 47 90 74 86]
 [96 76 40 98 77]
 [ 8 61 35  8 14]
 [62 33 14 62 70]
 [73 72 37 35 76]]

Resultant Matrix

[[ 49 -39 -31 -36 -64]
 [-24 -14  34  -1 -73]
 [ 75 -21  24  79  45]
 [ -6  23  14  12 -60]
 [ -2 -40  -1  21 -54]]


---
<h2 align = center><font color = '#46C7C7'>Multiplication</font></h2>

---


In [17]:

# Making 2 Random 5x5 Matrix

mat1 = np.random.randint(1,100 , size=(5,5),dtype='int16')
mat2 = np.random.randint(1,100 , size=(5,5),dtype='int16')

# Showing Mat1 and Mat2

print(f"\nMatrix 1\n")
print(mat1)

print(f"\nMatrix 2\n")
print(mat2)

# Multiplying the matrices

mat3 = np.matmul(mat1,mat2)

print(f"\nResultant Matrix\n")
print(mat3)




Matrix 1

[[35 66 30 94 15]
 [15 53  4 68 57]
 [15 21 95 92 89]
 [40 92 41 83 56]
 [81 63 49 68 44]]

Matrix 2

[[62 88 78 65 87]
 [50 21 67 85 88]
 [60 84 89 38  6]
 [51 79 78 50 51]
 [77 26 61  6 67]]

Resultant Matrix

[[13219 14802 18069 13815 14832]
 [11677  9623 13858  9374 13280]
 [19225 19323 23637 11504 14378]
 [18085 16909 22823 16464 19807]
 [17968 19083 22888 16146 19301]]


---
<h2 align = center><font color =#CC338B >Transpose a matrix and find the determinant and inverse of a matrix.
</font></h2>

---



<h3 align = center> Making a random 10x10 Matrix </h3>




In [22]:
mat = np.random.randint(1,100 , size=(10,10),dtype='int16')

# Showing Matrix

print(f"\nMatrix 1\n")
print(mat)



Matrix 1

[[32 67 14 32 62 59 91 28 20 17]
 [71 33 56  1 61 22  9 88 67 54]
 [89 43 30 26 99 69 69 60 43 68]
 [82 82 26 12 70  3 77 23 24 65]
 [11  9 14 92 25 76 33 36 57  6]
 [79  7 83 30 60 21 17  3 45 33]
 [19 70  5 76  7 75 90 10 77 46]
 [77 78 82  6 87 32 96 93 93 30]
 [13 43 44 70 72 77 49 45 71 53]
 [32 38 48 76 78 86 25 83 80 61]]


<h3 align = center> <font color = '#38ACEC'> Transposing the matrix </font></h3>

#### What is Transposing Matrix ?

A transposed matrix is obtained by swapping the rows and columns of the original matrix. 

In [23]:
transposedMatrix = np.transpose(mat)
print(f"\nTransposed Matrix\n")
print(transposedMatrix)


Transposed Matrix

[[32 71 89 82 11 79 19 77 13 32]
 [67 33 43 82  9  7 70 78 43 38]
 [14 56 30 26 14 83  5 82 44 48]
 [32  1 26 12 92 30 76  6 70 76]
 [62 61 99 70 25 60  7 87 72 78]
 [59 22 69  3 76 21 75 32 77 86]
 [91  9 69 77 33 17 90 96 49 25]
 [28 88 60 23 36  3 10 93 45 83]
 [20 67 43 24 57 45 77 93 71 80]
 [17 54 68 65  6 33 46 30 53 61]]


<h3 align = center> <font color = '#00A36C'> Finding Determinant </font></h3>

#### What is Determinant?

The determinant of a square matrix is a scalar value that can be computed from the elements of the matrix and has many important properties. 

In [25]:
determinant = np.linalg.det(mat)
print(f"\nDeterminant of Matrix 1: {determinant}\n")


Determinant of Matrix 1: -4.341495551896651e+16



<h3 align = center> <font color = '#FF6700'> Matrix Inverse </font></h3>

#### What is Matrix Inverse?

The inverse of a square matrix is another square matrix that has the same dimension as the original matrix and satisfies the following property:

mat * inverseMat = inverseMat * mat = I

where I is the identity matrix of the same size as the original matrix.

In [27]:
inverseMatrix = np.linalg.inv(mat)
print(f"\nInverse of Matrix\n")
print(inverseMatrix)



Inverse of Matrix

[[ 3.70386567e-02  8.97656992e-02 -1.44169079e-02 -5.64871930e-04
   3.96421170e-02  7.79249616e-05 -8.50517145e-03 -4.02132185e-02
   5.30774235e-02 -9.69808482e-02]
 [ 1.04085340e-01  2.14536366e-01 -6.17022373e-02 -1.17358387e-03
   7.16325377e-02 -9.76546888e-03 -2.39560864e-02 -9.69744409e-02
   1.58929153e-01 -2.22982723e-01]
 [-9.85664662e-02 -2.82799959e-01  4.64926567e-02 -1.55643181e-03
  -1.26172745e-01  3.24127342e-02  4.20202159e-02  1.22198654e-01
  -2.47154757e-01  3.45479082e-01]
 [-4.35523853e-02 -1.02973660e-01  1.21692911e-02  1.68632920e-02
  -2.25832738e-02  6.03848815e-03  6.98097967e-03  4.12092865e-02
  -8.50292956e-02  1.19061000e-01]
 [ 9.72360248e-02  2.59802992e-01 -4.84898081e-02  1.45592999e-03
   1.13731665e-01 -2.35106221e-02 -5.06765326e-02 -1.11932881e-01
   2.47251349e-01 -3.24614041e-01]
 [ 3.86702065e-02  5.01364061e-02 -6.15783263e-03 -2.08938787e-02
   1.45644828e-03  5.41400109e-03  4.54269051e-03 -2.74856244e-02
   2.30390445

---
<h1 align = center><font color =#D462FF > 2. Solving Linear Equations</font></h1>

---


<h2 align = center> <font color = '#FF0080'> Use NumPy to solve a system of linear equations. </font></h2>

#### What is Linear Equation?

A linear equation is an equation that can be written in the form of ax + by = c, where a, b, and c are constants and x and y are variables.





In [29]:
# Example Equation :
# x – y = 12 ---(1) 
# 2x + y = 22 ---(2)

# Converting the equation into matrix form Ax = b

a = np.array([[1,-1],[2,1]])
b = np.array([12,22])

x = np.linalg.solve(a,b)
print(x)


[11.33333333 -0.66666667]


#### Picture Solution

<img src="sol.png" alt="Linear Equations">




### Another Linear Equation Solution

In [31]:
# Equation
#  2x + 4y = 5
#  6x + 8y = 6

a = np.array([[2,4],[6,8]])
b= np.array([5,6])

x = np.linalg.solve(a,b)
x


array([-2.  ,  2.25])

<h2 align = center> <font color = '#FF0080'> Implement matrix factorization methods (LU decomposition, QR decomposition). </font></h2>

#### What is Matrix Factorization?

Matrix factorization is a method for breaking down a matrix into simpler matrices. There are two main types of matrix factorization:

1. LU Decomposition: This method decomposes a square matrix into a lower triangular matrix (L) and an upper triangular matrix (U).

2. QR Decomposition: This method decomposes a square matrix into a orthogonal matrix (Q) and a upper triangular matrix (R).

#### What is lower triangular matrix ?

A lower triangular matrix is a square matrix in which all elements above the main diagonal are zero.

#### What is upper triangular matrix ?

An upper triangular matrix is a square matrix in which all elements below the main diagonal are zero.



In [56]:
### Making a random square matrix

mat = np.random.randint(1,100 , size=(3,3),dtype='int16')

# Showing Matrix

print(f"\nMatrix 1\n")
print(mat)



Matrix 1

[[34 67 42]
 [ 7 42 49]
 [84 65 65]]


<h3 align = center> <font color = '#38ACEC'> LU Decomposition </font></h3>

#### Applications:

LU decomposition is used in various applications such as solving systems of linear equations, computing the inverse of a matrix, and solving linear least squares problems. It is particularly useful for solving systems of linear equations with a large number of variables.





In [57]:
import scipy.linalg
permutation,lower,upper = scipy.linalg.lu(mat)

print(f"\nLower Triangular Matrix (L):\n")
print(lower)
print(f"\nUpper Triangular Matrix (U):\n")
print(upper)

# As we know we can get our orignal matrix back by multiplying permutation matrix with lower triangular matrix .
# Then multiplying the resultant with upper triangular matrix. 

Q=np.dot(permutation,lower)

print("\nFinal Resultant Matrix\n")
print(np.dot(Q,upper))




Lower Triangular Matrix (L):

[[1.         0.         0.        ]
 [0.4047619  1.         0.        ]
 [0.08333334 0.89906377 1.        ]]

Upper Triangular Matrix (U):

[[84.       65.       65.      ]
 [ 0.       40.690475 15.690475]
 [ 0.        0.       29.476595]]

Final Resultant Matrix

[[34. 67. 42.]
 [ 7. 42. 49.]
 [84. 65. 65.]]


<h3 align = center> <font color = '#00A36C'> QR Decomposition </font></h3>

#### Usage:

QR decomposition is used in various applications such as solving systems of linear equations, computing the singular value decomposition (SVD), and finding the nearest matrix to a given matrix. It is particularly useful for solving linear least squares problems and computing the eigenvalues and eigenvectors of a matrix.



In [54]:
mat = np.random.randint(1,1000 , size=(4,4), dtype='int16')

# Showing Matrix

print(f"\nMatrix 1\n")
print(mat)

# QR Decomposition

Q,R = np.linalg.qr(mat)

print(f"\nOrthogonal Matrix (Q):\n")
print(Q)

print(f"\nUpper Triangular Matrix (R):\n")
print(R)

# Multiplying Q and R to get original matrix

print("\nFinal Resultant Matrix\n")
print(np.dot(Q,R))







Matrix 1

[[432 371 128 931]
 [153 109 140 209]
 [400 951 391 912]
 [576  37 114 907]]

Orthogonal Matrix (Q):

[[-0.51567287  0.01946936  0.59095981 -0.6200556 ]
 [-0.18263414 -0.02255828 -0.78260343 -0.59469973]
 [-0.47747488  0.81695085 -0.13534416  0.29375331]
 [-0.68756382 -0.57593695 -0.14135182  0.41901346]]

Upper Triangular Matrix (R):

[[ -837.74041325  -690.74022316  -356.64985868 -1577.33944679]
 [    0.           760.37487078   253.10488868   236.0956489 ]
 [    0.             0.          -102.95529917   134.97948954]
 [    0.             0.             0.           -53.61577717]]

Final Resultant Matrix

[[432. 371. 128. 931.]
 [153. 109. 140. 209.]
 [400. 951. 391. 912.]
 [576.  37. 114. 907.]]


<h3 align = center> <font color = '#0090AE'> Application </font></h3>

#### What is singular matrix ? 

A singular matrix is a square matrix that does not have an inverse. In other words, its determinant is zero. This means that the system of linear equations Ax = b has either no solution, infinitely many solutions, or a unique solution depending on the values of the constants a1, a2,..., an.


In [62]:

# For example, we can use QR decomposition to solve a system of linear equations.

# Equation

#  2x + 4y + 6z = 10
#  3x + 6y + 9z = 15
#  4x + 8y + 12z = 20

a = np.array([[2,4,6],[3,6,9],[4,8,12]])
b= np.array([10,15,20])

# sol = np.linalg.solve(a,b) This Can't be run because the matrix is singular. QR decomposition or other methods can be used to find a least-squares solution in such cases.

# Perform QR decomposition
Q, R = np.linalg.qr(A)

# Solve for x, y, z
Q_T_b = np.dot(Q.T, b)
x = np.linalg.solve(R, Q_T_b)

print(f"\nSolution: x = {x[0]}, y = {x[1]}, z = {x[2]}\n")




Solution: x = -0.5790877191984275, y = 0.9126028444406878, z = -0.6563797528836096



---
<h1 align = center><font color =#AABB44 > 3. Eigenvalues and Eigenvectors</font></h1>

---



#### What is Eigenvalues ? 

Eigenvalues are scalar values associated with a square matrix. They are solutions to the characteristic equation det(A - λI) = 0, where A is the matrix and λ is the eigenvalue. Eigenvalues can be found using the numpy.linalg.eig() function.

#### What is Eigenvectors ?

Eigenvectors are non-zero vectors that, when multiplied by a square matrix, produce a scaled version of themselves. They are related to eigenvalues and are found using the numpy.linalg.eig() function.

#### What is the relationship between Eigenvalues and Eigenvectors ?

Eigenvalues and eigenvectors have a significant relationship in linear algebra. They are used to analyze the properties of linear transformations and solve systems of linear equations. For example, eigenvalues and eigenvectors can be used to determine the stability of a system of linear differential equations, to find the principal components of a dataset, and to perform PCA (Principal Component Analysis) for dimensionality reduction.



<h2 align = center> <font color = '#FF0080'> Calculate the eigenvalues and eigenvectors of a given matrix.. </font></h2>

In [80]:
mat = np.array([[2, 1, 0],
                [1, 3, 1],
                [0, 1, 2]])

# Calculate eigenvalues and eigenvectors

eigenvalues, eigenvectors = np.linalg.eig(mat)

print(f"\nEigenvalues:\n")
print(eigenvalues)

print(f"\nEigenvectors:\n")

for i in range(len(eigenvalues)):
    print(f"\nEigenvector {i+1}:\n")
    print(eigenvectors[:,i])


Eigenvalues:

[4. 2. 1.]

Eigenvectors:


Eigenvector 1:

[-0.40824829 -0.81649658 -0.40824829]

Eigenvector 2:

[ 7.07106781e-01 -3.45742585e-16 -7.07106781e-01]

Eigenvector 3:

[ 0.57735027 -0.57735027  0.57735027]


<h2 align = center> <font color = '#FF0080'> Verify the results by reconstructing the original matrix.
 </font></h2>

In [93]:
# Formula for reconstructing the original matrix

#A = P Λ P^-1.

# Reconstruct the original matrix

A = np.diag(eigenvalues)
P = eigenvectors

reconstructedMatrix = np.dot(np.dot(P,A),np.linalg.inv(P))


print(f"\nReconstructed Matrix:\n")
print(reconstructedMatrix)



Reconstructed Matrix:

[[2.00000000e+00 1.00000000e+00 3.34106299e-16]
 [1.00000000e+00 3.00000000e+00 1.00000000e+00]
 [2.27686080e-16 1.00000000e+00 2.00000000e+00]]


---
<h1 align = center><font color =#BF4311 > 4. Vector Operations</font></h1>

---



#### What is a Vector ? 

A vector is a geometric object that has magnitude (length) and direction. In other words, a vector is a one-dimensional array of numbers. Vectors can be represented using arrow notation, where the arrow starts at the origin (0, 0, 0) and points in the specified direction.

<h2 align = center> <font color = '#FF0080'> Perform basic vector operations (addition, dot product, cross product). </font></h2>




### Addition

In [94]:
# Making 2 vectors

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Adding vectors

result_addition = v1 + v2

print(f"\nAddition Result:\n")
print(result_addition)



Addition Result:

[5 7 9]


### Dot Product

what is dot product ? 

dot product is a scalar value that represents the magnitude of one vector in the direction of another vector. It is calculated by multiplying the corresponding components of the two vectors and then summing the results.

Example Code is given below:

In [95]:
# Dot product

result_dot_product = np.dot(v1, v2)

print(f"\nDot Product Result:\n")
print(result_dot_product)


Dot Product Result:

32


### Cross Product

what is cross product? 

cross product is a vector that results from the multiplication of two vectors. It is calculated by finding the determinant of a 2x2 matrix formed by the two vectors.

Example Code is given below:

In [98]:
#Cross product

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])



result_cross_product = np.cross(v1, v2)

print(f"\nCross Product Result:\n")
print(result_cross_product)



Cross Product Result:

[-3  6 -3]


<h2 align = center> <font color = '#FF0080'> Normalize a vector and compute vector norms. </font></h2>



#### What is normalization of a vector?

Normalization is the process of scaling a vector to have a magnitude of 1. It is done by dividing the vector by its length.

#### What is vector norms ?

Vector norms are measures of the size or length of a vector. There are several types of vector norms, such as:

- Euclidean norm (L2 norm): sqrt(sum of squares of vector components)
- Manhattan norm (L1 norm): sum of absolute values of vector components
- Maximum norm (L Infinity norm): maximum absolute value of vector components

#### Vector Normalization


In [103]:
# Making a vector

v = np.array([8, 22, 100])

# Normalizing the vector

normalized_v = v / np.linalg.norm(v)

print(f"\nNormalized Vector:\n")
print(normalized_v)



Normalized Vector:

[0.07789417 0.21420895 0.97367706]


#### Results

As we can see, the normalized vector has a magnitude of 1, and its elements are scaled such that the vector points in the same direction as the original vector.

#### Using Euclidean norm

In [111]:

# Calculating Euclidean norm

euclideanNorm = np.linalg.norm(v)

print(f"\nEuclidean Norm:\n")
print(euclideanNorm)

normalized_v = v / euclideanNorm

print(f"\nNormalized Vector Using Euclidean Norm:\n")
print(normalized_v)


Euclidean Norm:

102.70345661174214

Normalized Vector Using Euclidean Norm:

[0.07789417 0.21420895 0.97367706]


In [110]:
# Using Manhattan Norm

manhattanNorm = np.linalg.norm(v, ord=1)

print(f"\nManhattan Norm:\n")
print(manhattanNorm)
# Using Maximum Norm

normalized_v = v / manhattanNorm

print(f"\nNormalized Vector Using Manhattan Norm:\n")
print(normalized_v)




Manhattan Norm:

130.0

Normalized Vector Using Manhattan Norm:

[0.06153846 0.16923077 0.76923077]


In [109]:
# Using Infinity Norm

infinityNorm = np.linalg.norm(v, ord=np.inf)

print(f"\nMaximum Norm:\n")
print(infinityNorm)

normalized_v = v / infinityNorm

print(f"\nNormalized Vector Using Infinity Norm:\n")
print(normalized_v)




Maximum Norm:

100.0

Normalized Vector Using Infinity Norm:

[0.08 0.22 1.  ]


---
<h1 align = center><font color =#5865F2 > 5. Matrix Decomposition</font></h1>

---





Understand and implement Principal Component Analysis (PCA) using SVD.

<h2 align = center> <font color = '#FF0080'> Understand and implement Principal Component Analysis (PCA) using SVD.
  </font></h2>




#### What is Principal Component Analysis ?

Principal Component Analysis (PCA) is a statistical technique used to reduce the dimensionality of a dataset while retaining as much information as possible. It finds the principal components, or directions of maximum variance in the data, and projects the data onto these principal components to create a new, lower-dimensional representation.

#### What is Singular Value Decomposition (SVD) ?

Singular Value Decomposition (SVD) is a matrix decomposition technique that factorizes a matrix into three matrices: U, Singular, and V^T. The U matrix contains the left singular vectors, the Singular matrix contains the singular values, and the V^T matrix contains the right singular vectors.


---
<h1 align = center><font color = #64E986 >Calculus Tasks</font></h1>

---



---
<h2 align = center> <font color = '#FE632A'> 

Numerical Differentiation

  </font></h2>

---


<h2 align = center> <font color = '#FF0080'> 

Use NumPy to compute the numerical derivative of a given function.
  </font></h2>



#### What is Numerical derivative of function?

Numerical derivative is a technique used to approximate the derivative of a function by computing the difference between the function values at two points, divided by the difference between the two points.



In [122]:
# Given function

# f(x) = x^3 + x^2 + 5

def f(x):
    return x**3 + x**2 + 5



# Numerical Derivative 

def numericalDerivative(f, x, h=1e-6):
    return (f(x + h) - f(x - h)) / (2 * h)

# Compute numerical derivative using forward difference method

x = np.arange(1,5)


# Compute numerical derivative using central difference method

print(f"\nNumerical derivative using central difference method at x = {x}:")
print(numericalDerivative(f, x))



# Now Checking the derivative using analytical method
def derivative(x): # Returning the derivative of function
    return 3 * x**2 + 2 * x 

print(f"\nAnalytical derivative at x = {x}:")
print(derivative(x))


# As we can see analytical derivatives and numerical derivatives are approximately same






Numerical derivative using central difference method at x = [1 2 3 4]:
[ 5.         16.         33.00000001 56.00000001]

Analytical derivative at x = [1 2 3 4]:
[ 5 16 33 56]


<h2 align = center> <font color = '#FF0080'> 

Implement forward, backward, and central difference methods for differentiation

  </font></h2>



#### Forward Method

Formula:

f'(x) = (f(x + h) - f(x)) / h



In [124]:
# Given Function

# f(x) = 3x^2 + 2

def f(x):
    return 3 * x**2 + 2

# Forward difference method

def forwardDifference(x, h=1e-6):
    return (f(x + h) - f(x)) / h

# Compute forward difference method

x = np.arange(1,5)

print(f"\nForward difference method at x = {x}:")
print(forwardDifference(x))

# Now Checking the derivative using analytical method

def derivative(x): # Returning the derivative of function
    return 6 * x

print(f"\nAnalytical derivative at x = {x}:")
print(derivative(x))





Forward difference method at x = [1 2 3 4]:
[ 6.000003   12.000003   18.000003   24.00000299]

Analytical derivative at x = [1 2 3 4]:
[ 6 12 18 24]


#### Backword Method

Formula:

f'(x) = (f(x) - f(x - h)) / h

In [126]:
# Given Function

# f(x) = 3x^2 + 2

def f(x):
    return 3 * x**2 + 2

# Backward difference method

def backwardDifference(x,h = 1e-6):
    return ((f(x) - f(x-h))/h)

# Compute backward difference method

x = np.arange(1,5)

print(f"\nBackward difference method at x = {x}:")
print(backwardDifference(x))



Backward difference method at x = [1 2 3 4]:
[ 5.999997 11.999997 17.999997 23.999997]


#### Central difference method

Formula:

f'(x) = (f(x + h) - f(x - h)) / (2h)


In [128]:

def f(x):
    return 3 * x**2 + 2

# Central difference method

def centralDifference(x,h = 1e-6):
    return ((f(x+h) - f(x-h))/(2*h))

# Compute central difference method

x = np.arange(1,5)

print(f"\nCentral difference method at x = {x}:")
print(centralDifference(x))


Central difference method at x = [1 2 3 4]:
[ 6. 12. 18. 24.]



---
<h2 align = center> <font color = '#7F38EC'> 

Numerical Integration


  </font></h2>

---



#### What is Numerical Integration

Numerical integration is a technique used to approximate the definite integral of a function by approximating the area under the curve of the function over a given interval. There are two main types of numerical integration methods: trapezoidal rule and Simpson's rule.

<h2 align = center> <font color = '#FF0080'> 

Use NumPy to compute the numerical integral of a given function.

  </font></h2>



In [134]:

# Define the function
# f(x) = x^2 + 3x + 2
def f(x):
    return x**2 + 3*x + 2

# Intervals [a, b]
a, b = 0, 4

# Number of points
num_points = 500

# Create an array of x values from a to b
x = np.linspace(a, b, num_points)


# Compute the numerical integral using the trapezoidal rule
integral = np.trapezoid(f(x), x)

print("Numerical integral of f(x) from {} to {} is: {}".format(a, b, integral))


Numerical integral of f(x) from 0 to 4 is: 53.333376171180035


<h2 align = center> <font color = '#FF0080'> 
Implement the trapezoidal rule and Simpson's rule for integration.
  </font></h2>



### Using Trapezoidal Rule

Trapezoidal Rule:

Integral[a, b] = (h/2) * [f(x0) + 2*f(x1) + 2*f(x2) +... + 2*f(xn-1) + f(xn)]

In [136]:


# Define the function
# f(x) = x^2 + 3x + 2
def f(x):
    return x**2 + 3*x + 2

# Intervals [a, b]
a, b = 0, 4

# Number of points
num_points = 500

# Create an array of x values from a to b
x = np.linspace(a, b, num_points)


# Compute the numerical integral using the trapezoidal rule
integral = np.trapezoid(f(x), x)

print(f"Numerical integral of f(x) from {a} to {b} is: {integral}")



Numerical integral of f(x) from 0 to 4 is: 53.333376171180035


### Using Simson's Rule For Integration
