***Serial No : 19***

In [2]:
import numpy as np

# Indexing And Slicing

1. Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1).

In [12]:
# Making 1D Array Filled with numbers from 1 to 36
array = np.arange(1,37)
print(array)
print()
# Changing it into 6x6 matrix or (6,6) shape
array=array.reshape(6,6)
print(array)
print()
# Now Slicing the 2x2 matrix from (1,1) element
print(array[1:3 , 1:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

[[ 8  9]
 [14 15]]


2. From a 3D array of shape (3, 2, 1), extract all elements in the first two rows and all columns of the second slice along the third axis.

In [18]:
# Making 1D Array Filled with numbers from 1 to 6
array = np.arange(1,7)
print(array)
print()
# Changing it into(3,2,1) shape
array=array.reshape(3,2,1)
print(array)
print()
# Extracting All elements from first 2 rows and all the columns of 2nd slice along the third axis
print(array[1,:2,:])

[1 2 3 4 5 6]

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]

[[3]
 [4]]


3. Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 6].


In [27]:
# Making 1D Array Filled with random numbers from 10 to 300
array = np.random.randint(10,310,10)
print(array)
print()

#Fancy Indexing

# Integer Array Indexing
indices = np.array([1,3,4,6])
elements = array[indices]
print(elements)

# Boolean Array Indexing

indices = np.array([False,True,False,True,True,False,True,False,False,False])
element = array[indices]
print(element)

[193 203 244  24 182  85  22  85  69 240]

[203  24 182  22]
[203  24 182  22]


4. Given a 2D array, use fancy indexing to select rows [0, 2, 2] and columns [1, 3].

In [42]:
# Making 1D Array Filled with numbers from 1 to 16
array = np.arange(1,17)
print(array)
print()
#Reshaping it in to shape(2,2) 
array=array.reshape(4,4)
print(array)
print()

#Now Finding Rows
print("Rows")
rows_indices = np.array([0,2,2])
rows = array[rows_indices]
print(rows)
print()

#Now Finding Columns
print("Columns")
columns_indices = np.array([1,3])
columns = array[:,columns_indices]
print(columns)




[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Rows
[[ 1  2  3  4]
 [ 9 10 11 12]
 [ 9 10 11 12]]

Columns
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


5. From a 1D array of random integers, extract all elements that are greater than 8.

In [57]:
# Making 1D Array Filled with random numbers from 1 to 300
array = np.random.randint(1,20,20)
print(array)
array = array[array > 8]
print()
print("Answer\n")
print(array)


[ 1  6  2  3  6  5 18 17  5 16 14  7  5 19 16  7  9 11 17 13]

Answer

[18 17 16 14 19 16  9 11 17 13]


6. Given a 2D array of shape (6, 6), replace all elements greater than 13 with the value 0.

In [75]:
# Making 1D Array Filled with numbers from 1 to 36
array = np.random.randint(1,20,36)
print(array)
print()
# Changing it into 6x6 matrix or (6,6) shape
array=array.reshape(6,6)
print(array)
print()

# Now we are replacing number greater than 13 with the value of 0



array[array>13]=0
print(array,'\n')

# Using numpy built in function

finalArray = np.where(array>13 , 0,array)
print(finalArray)




[ 8 11  9 10 11  4  2  4 16  8 10  5  2 19 13  9 19 17 12 14  3 16 19 19
 19  8 10 18  9  5 13 19 15 16  2 11]

[[ 8 11  9 10 11  4]
 [ 2  4 16  8 10  5]
 [ 2 19 13  9 19 17]
 [12 14  3 16 19 19]
 [19  8 10 18  9  5]
 [13 19 15 16  2 11]]

[[ 8 11  9 10 11  4]
 [ 2  4  0  8 10  5]
 [ 2  0 13  9  0  0]
 [12  0  3  0  0  0]
 [ 0  8 10  0  9  5]
 [13  0  0  0  2 11]] 

[[ 8 11  9 10 11  4]
 [ 2  4  0  8 10  5]
 [ 2  0 13  9  0  0]
 [12  0  3  0  0  0]
 [ 0  8 10  0  9  5]
 [13  0  0  0  2 11]]


# Broadcasting

1. Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).

In [86]:
# Making 2D array of shape (4,3)
array1 = np.arange(1,13).reshape(4,3)
print('\n Array of shape(4,3)')
print(array1)

# Making 1D array of shape (1,3)
print('\nArray of shape (1,3)',)
array2 = np.arange(1,4).reshape(1,3)
print(array2)

finalArray = array1 + array2
print(f"\nFinal Array\n{finalArray}")



 Array of shape(4,3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Array of shape (1,3)
[[1 2 3]]

Final Array
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


2. Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).

In [88]:
# Making 2D array of shape (3,3)
array1 = np.arange(1,10).reshape(3,3)
print('\n Array of shape(3,3)')
print(array1)

# Making 1D array of shape (1,3)
print('\nArray of shape (1,3)',)
array2 = np.arange(1,4).reshape(1,3)
print(array2)

finalArray = array1 * array2
print(f"\nFinal Array\n{finalArray}")



 Array of shape(3,3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array of shape (1,3)
[[1 2 3]]

Final Array
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


3. Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.


In [94]:
array1 = np.arange(3).reshape(3,1)
print(f"Array of shape (3,1)\n {array1} \n")
array2 = np.arange(4).reshape(1,4)
print(f"Array of shape (1,4) \n {array2} \n")

array3 = array1 + array2 
print(f"A new array of shape (3,4) will be create \n {array3} \narray3")


Array of shape (3,1)
 [[0]
 [1]
 [2]] 

Array of shape (1,4) 
 [[0 1 2 3]] 

A new array of shape (3,4) will be create 
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]] 
array3


4. Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.

In [104]:
array3d = np.arange(24).reshape(2,3,4)
print(f"3D Array of shape (2,3,4)\n{array3d}\n")

array2d = np.arange(12).reshape(3,4)
print(f"2D Array of shape (3,4)\n{array2d}\n")


finalArray = array3d + array2d
print(f"3D Array of shape (2,3,4)\n{finalArray}\n")

3D Array of shape (2,3,4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

2D Array of shape (3,4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

3D Array of shape (2,3,4)
[[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[12 14 16 18]
  [20 22 24 26]
  [28 30 32 34]]]



# See More

1. Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.


In [117]:
array2d = np.arange(36).reshape(6,6)
print(f"\n Orignal 2D Array:\n{array2d}")


slicedArray = array2d[::2,::2]
print(f"\n Sliced Array:\n{slicedArray}")

array1d = np.array([1])
print(f"\n 1D Array:\n{finalArray}")

finalArray=slicedArray + array1d
print(f"\n Final Array:\n{finalArray}")


 Orignal 2D Array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

 Sliced Array:
[[ 0  2  4]
 [12 14 16]
 [24 26 28]]

 1D Array:
[[ 1  3  5]
 [13 15 17]
 [25 27 29]]

 Final Array:
[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


2. From a 3D array of shape (3, 2, 1), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.

In [19]:
print(f"Orignal 3d Array\n ")
array3d = np.arange(6).reshape(3,2,1)
print(array3d)

#sub_array (Extracting first element of every slice)
print(f"Extracted Sub Array\n ")
subArray = array3d[:,:1,:1]
print(subArray)
print()

#2D Array
print(f"Orignal 2d Array\n ")

array2d = np.array([[1],[2]])
print(array2d)
print()

print(f"Final Array\n ")

finalArray = array2d - subArray
print(finalArray)

Orignal 3d Array
 
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]
Extracted Sub Array
 
[[[0]]

 [[2]]

 [[4]]]

Orignal 2d Array
 
[[1]
 [2]]

Final Array
 
[[[ 1]
  [ 2]]

 [[-1]
  [ 0]]

 [[-3]
  [-2]]]


3. Given a 2D array, extract the diagonal elements and create a 1D array.

In [26]:
print(f"\n2D Array\n")
array2d = np.arange(36).reshape(6,6)
print(array2d)

print(f"\nDiagonals\n")

diagonals = np.diag(array2d)
print(diagonals)




2D Array

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Diagonals

[ 0  7 14 21 28 35]


4. Use slicing to reverse the order of elements in each row of a 2D array

In [ ]:
print(f"\nOrignal 2D Array")
array2d = np.arange(25).reshape(5,5)
print(array2d)

print(f"\nReversed 2D Array\n")
reversedarray2d = array2d[::,::-1]
print(reversedarray2d)

5. Given a 3D array of shape (7, 6, 5), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.


In [44]:
print(f"\n 3D Array Of Shape(7,6,5)\n")
array3d = np.arange(210).reshape(7,6,5)
print(array3d)

print(f"\n Sub Array Of Shape(2,3,4)")
subArray = array3d[:2 , :3 , :4]
print(subArray)

print(f"\n 1D Array Of Shape (,4)")
array1d = np.array([1,2,3,4])

print(f"\nBroadcasting\n")
finalArray = array1d + subArray
print(finalArray)



 3D Array Of Shape(7,6,5)

[[[  0   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]
  [ 15  16  17  18  19]
  [ 20  21  22  23  24]
  [ 25  26  27  28  29]]

 [[ 30  31  32  33  34]
  [ 35  36  37  38  39]
  [ 40  41  42  43  44]
  [ 45  46  47  48  49]
  [ 50  51  52  53  54]
  [ 55  56  57  58  59]]

 [[ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]
  [ 75  76  77  78  79]
  [ 80  81  82  83  84]
  [ 85  86  87  88  89]]

 [[ 90  91  92  93  94]
  [ 95  96  97  98  99]
  [100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]

 [[120 121 122 123 124]
  [125 126 127 128 129]
  [130 131 132 133 134]
  [135 136 137 138 139]
  [140 141 142 143 144]
  [145 146 147 148 149]]

 [[150 151 152 153 154]
  [155 156 157 158 159]
  [160 161 162 163 164]
  [165 166 167 168 169]
  [170 171 172 173 174]
  [175 176 177 178 179]]

 [[180 181 182 183 184]
  [185 186 187 188 189]
  [190 191 192 193 194]
  [195 196 197 198 199]


6. Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.

In [46]:
# 2D Array Of Shape (5, 5)
array2d = np.arange(16).reshape(4,4)

print("Original array:")
print(array2d)

# Use slicing and broadcasting to set the last column to the sum of the first two columns for each row
array2d[:, -1] = array2d[:, 0] + array2d[:, 1]

print("\nModified array:")
print(array2d)


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Modified array:
[[ 0  1  2  1]
 [ 4  5  6  9]
 [ 8  9 10 17]
 [12 13 14 25]]
